name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 10
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@ghtoken
        env:
          FOLDER: build
          BUILD_SCRIPT: yarn install && yarn build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
