name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 10
      - name: Install, Build and Deploy
        run: |
          yarn install
          yarn deploy
