name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          version: 10
      - name: Install and Buil
        run: |
          yarn install
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          FOLDER: build
          BRANCH: gh-pages
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
